### ISSUE TITLE
nonce value of 128-bits

### ISSUE THREAD

**Issue by dasj19** [wyattoday/mod_cspnonce#2]
Hi, is it possible to increase the nonce size?
This validator: https://cspvalidator.org/ says that CSP specification recommends nonce of 128-bits (before encryption)

**Comment by wyattoday** [comment]
I was looking for the actual source of the recommendation, and found it here: https://w3c.github.io/webappsec-csp/#security-nonces

The recommendation doesn't seem to be based on research (it's just a nice round number -- which ironically doesn't divide evenly to fit inside a bse64 value without padding).

That being said, yeah, we can do that. It'll be 144-bit, not 128-bit, because 144-bit actually divides correctly. Whoever made up that number should fix the imaginary number to actually make practical sense.

**Comment by wyattoday** [comment]
1.3 is now out and this has been addressed.

**Comment by dasj19** [comment]
Thank you very much.
I packaged your module for NixOS  https://github.com/NixOS/nixpkgs/pull/93527 and I am running it on a public searx instance https://searx.gnu.style/ .
Keep up the good work
